version: "3.7"

services:
  web:
    image: httpd:latest
    container_name: website
    ports:
      - "8081:80"
    volumes:
      - ./frontend:/usr/local/apache2/htdocs/

  mysql_db_container:
    image: mysql:latest
    container_name: mysql
    hostname: mysql_host ## agregado con video 36
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: codopass123
      MYSQL_DATABASE: expense_db
    ports:
      - 3306:3306

  ## Agregado con video 36
  django:
    build: ./backend
    container_name: django
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - mysql
  ## Fin Agregado

  # adminer_container:
  #   image: adminer:latest
  #   environment:
  #     ADMINER_DEFAULT_SERVER: mysql_db_container
  #   ports:
  #     - 8080:8080
